### ISSUE TITLE
After releasing (tag and push), run "postreleasy" script if it exists

### ISSUE THREAD

**Issue by firstdoit** [vtex/releasy#13]
If `package.json` defines a `postreleasy` script in the `scripts` section, call `npm run postreleasy` after a successful release.

For example, Storefront apps will be able to define:

```
"scripts": {
  "postreleasy": "vtex publish"
}
```

And publish an app with `releasy minor`.

**Comment by brenoc** [comment]
@firstdoit I didn't get it.

1. You run `npm run publish`
2. It will run the `vtex publish` command
3. Then you run `releasy minor'

Is that right?

**Comment by firstdoit** [comment]
Noope.

You only call `releasy`. It calls the `publish` script, if it's defined.
