### ISSUE TITLE
Releasy não incrementa numero da tag

### ISSUE THREAD

**Issue by paulocmi** [vtex/releasy#27]
Ao utilizar o releaqsy para gerar uma nova tag, a mesma nao é incrementada.

Versão usada:
$ releasy --version
1.5.6

paulo@DESKTOP-6DN4LC0 MINGW64 /c/Vtex/heimdall-ui (master)
$ releasy minor
Release: minor
Old version: 0.2.0-beta
New version: 0.2.0-beta

**Comment by firstdoit** [comment]
@paulocmi pode tentar com a versão 1.6.1? E pode dar mais detalhes sobre como reproduzir?

**Comment by firstdoit** [comment]
@paulocmi corrigido na versão 1.7.0!
