### ISSUE TITLE
Push a single tag by default

### ISSUE THREAD

**Issue by dfosco** [vtex/releasy#30]
I have been receiving this warning for a while, and @koz warned me that it was because I had a tag in my local repo that was already pushed by someone else. It doesn't break my release, but it's a nagging warning.

![pasted_image_at_2017_05_19_13_37](https://cloud.githubusercontent.com/assets/3229933/26257963/05ae999e-3c99-11e7-8476-b616f5b6a530.png)

Deleting the tag was easy enough, but @gugiserman raised the question *why* we whould be pushing all tags at once in the first place?

We propose to change releasy's default behavior to push *only* the latest tag created, and leave the responsibility to push all tags or specific ones to the user, via git main interface.

Thoughts?

**Comment by dfosco** [comment]
ping @tamorim and @firstdoit that were the most active contributors here

**Comment by firstdoit** [comment]
Oh yes!

Why: because when I did this 4 years ago I didn't know you _could_ send only the latest tag 😂 

PR accepted :)
