### ISSUE TITLE
Prompt warning: "(node:71374) Warning: Accessing non-existent property 'padLevels'"

### ISSUE THREAD

**Issue by ganobrega** [vtex/releasy#61]
When I use **releasy** via the `npx releasy` command, the prompt is misconfigured.

## Expected Behavior
<img width="732" alt="Captura de Tela 2021-06-08 às 12 57 04" src="https://user-images.githubusercontent.com/4602864/121218497-2ac30300-c859-11eb-9b27-698a0df9b625.png">

## Current Behavior
When I run the command, the prompt appears mangled with a warning.

<img width="1279" alt="Captura de Tela 2021-06-08 às 12 41 36" src="https://user-images.githubusercontent.com/4602864/121216464-4b8a5900-c857-11eb-95b6-fe72d57cd5af.png">

The output:
```
prompt: Are you sure?:  (yes) (node:83710) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
```

## Possible Solution
1. Fix the `vtex release` to support the `_releasy.yaml` file.
2. Fix the `releasy` warning

## Steps to Reproduce (for bugs)
1. Create the following files within an app
```yaml
# _releasy.yaml
filename: manifest.json
type: minor
stable: true
display-name: true
```
2. Run the command `npx releasy`

## Context
My repository contains the following apps:
- 1x (Store Theme)
- 1x  (Checkout UI Custom)
- 2x (My Account Extension App)

I developed a bash script that releases all apps inside the repository and use the `npx releasy` command to make the release in each app. 

I don't use the `vtex release` command because it doesn't support the `_releasy.yaml` file.

I just use the `_releasy.yaml` file because  there is a feature called `display-name` which sets the tag name exactly the same as the package name.

## Your Environment

* Version used: `1.12.0`
* Environment name and version:
  * **Node**: `v14.15.1`
  * **Npm**: `v6.14.8` 
* Operating System and version (desktop or mobile): `macOS Catalina 10.15.7` and `Windows 10 Pro 20H2 (Build: 1904.985)`

**Comment by lucasecdb** [comment]
fixed on #67
